
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: slack_collect_msg_development
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: mysql2://rails_user:password@db:3306/slack_collect_msg_development
      RAILS_ENV: development
    stdin_open: true
    tty: true

  test_db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: slack_collect_msg_test
    ports:
      - "3307:3306"
    volumes:
      - test_mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  test_mysql_data:
  bundle_cache: